# Model arguments
model_name_or_path: "stabilityai/StableBeluga-7B"
use_flash_attention_2: true
torch_dtype: auto

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments

dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.5
do_eval: true
evaluation_strategy: "steps"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1536
max_prompt_length: 512
num_train_epochs: 1
optim: rmsprop
output_dir: data/PE-7b-lora # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: null
seed: 42
warmup_ratio: 0.1