# Model arguments
model_name_or_path: "mistralai/Mistral-7B-v0.1"
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 2.0e-5
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_seq_length: 1536
max_steps: -1
output_dir: data/PE_Mistral_7b_sft
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 200
save_total_limit: null
seed: 42
warmup_ratio: 0.1