# Model arguments
model_name_or_path: meta-llama/Llama-2-7b-chat-hf
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.5
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 3.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1536
max_prompt_length: 768
num_train_epochs: 3
optim: rmsprop
output_dir: data/hailey-new-PE-runs/PE_Llama_2_chat_7b_rlhf_only
per_device_train_batch_size: 8
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 500
save_total_limit: null
seed: 42
warmup_ratio: 0.1
